on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64, x86_64]

    env:
      DEBUG_ANDROID_API_LEVEL: 33
      GENERATOR: "Ninja"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
          add-to-path: true

      - name: Export ANDROID_NDK
        run: echo "ANDROID_NDK=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Build Android aarch64
        if: matrix.arch == 'aarch64'
        run: make debug-aarch64

      - name: Build Android x86_64
        if: matrix.arch == 'x86_64'
        run: make debug-x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: freecam-${{ matrix.arch }}-android-debug
          path: |
            build/**/*.so

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: x86_64
            cmake_arch: x64
          - arch: x86
            cmake_arch: Win32

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A ${{ matrix.cmake_arch }} 
          -D CMAKE_BUILD_TYPE=Debug

      - name: Build
        run: >
          cmake --build build
          --config Debug

      - uses: actions/upload-artifact@v4
        with:
          name: freecam-${{ matrix.arch }}-windows-debug
          path: |
            build/**/*.dll
